---
title: Install Raspberry Pi Desktop on your PC or Mac
hero_image: images/banner.png
description: Breathe new life into an old computer by installing Raspberry Pi Desktop
  on it
version: 4
listed: true
copyedit: true
last_tested: '2018-09-19'
steps:
- title: Introduction
  completion: engaged
- title: Download Raspberry Pi Desktop
- title: Create a USB drive installer
- title: Boot from the USB drive
- title: Install Raspberry Pi Desktop
  completion: internal
- title: Start up Raspbery Pi Desktop
- title: What next?
