title: install-raspberry-pi-desktop
hero_image: images/banner.png
description: install-raspberry-pi-desktop description
version: 4
listed: false
copyedit: false
last_tested: "2018-09-19"
steps:
  - title: Introduction
  - title: What you will need
  - title: Step title
