title: Install Raspberry Pi Desktop
hero_image: images/banner.png
description: Breathe new life into an old computer by installing Raspberry Pi Desktop on it
version: 4
listed: false
copyedit: false
last_tested: "2018-09-19"
steps:
  - title: Introduction
  - title: Download Raspberry Pi Desktop
  - title: Create a USB drive installer
  - title: Install Raspberry Pi Desktop
  - title: Start up Raspbery Pi Desktop
  - title: What next?

